### ISSUE TITLE
Discrepancy in Transaction Count Due to Re-Broadcasting Old Transactions

### ISSUE THREAD

**Issue by fmosterts** [flashbots/mempool-dumpster#21]
**Description:**

While analyzing the data, we observed a significant delta in the unique transactions between us and other providers. The major difference is due to other providers re-broadcasting old (weeks or months old) transactions that were never included on-chain. This leads to a skewed perspective on the actual unique transactions.

Addressing this issue is crucial as it accounts for around 5-7% of daily transactions the dumpster logs daily.

**Details:**

- **From a random sample of 1,000 transactions seen only by a single provider around 90% (i.e., 890 out of 1,000) were recognized as transactions observed weeks or even months ago in our internal database.**
- To illustrate this issue further, I’ve attached the following samples, selecting only tx_hashes, which Fiber did not log from the `2023-09-19_sourcelog`:
  - [sample_1.csv](https://github.com/flashbots/mempool-dumpster/files/12682195/sample_1.csv), includes the date-times of when Fiber first noticed the hashes. If `NaN` means that Fiber never saw the specific hash (therefore an actual unique transaction).
  - Aggregate view of when Fiber logged transactions other providers have seen on 9/19:  
  ![sample_2](https://github.com/flashbots/mempool-dumpster/assets/84743718/46903fcc-b53e-4e2d-a1b9-de55189c465f)

**Proposed Solutions & Next Steps:**

1. Review the attached samples and the date-times associated with each transaction.
2. In general terms:
    1. Open a discussion on how devp2p manages duplicates and re-broadcasting of old transactions at the p2p level. 
3. Regarding Flashbots Dumpster:
    1. As the issue is being investigated, add a disclaimer to the `Exclusive tx (single source)` per provider summary stats, stating that the delta between providers could be due to old re-broadcasted transactions. 
    2. **We're open to integrating [FiberDB](https://fiber.chainbound.io/docs/fiberdb) in the Flashbots Dumpster to improve the quality of the database and verify that transactions have not been broadcasted in any previous period.**

**Comment by metachris** [comment]
Thanks a lot for your support on validating the data and arriving at better metrics!

How do you feel about the most recent improvements? I.e. https://mempool-dumpster.flashbots.net/ethereum/mainnet/2023-09/2023-09-23_summary.txt

The data now checks for inclusion of transactions and discards any transactions that were included >12s before arriving at the mempool dumpster collector.

**Comment by 0xJchen** [comment]
> other providers re-broadcasting old (weeks or months old) transactions that were never included on-chain.

Adding to the discussion, there are also ~50 transactions in the sample dataset that were already confirmed transactions a long time ago (negative value in 'time_delta_hours').

[sample_1_with_time_delta.csv](https://github.com/flashbots/mempool-dumpster/files/12709663/sample_1_with_time_delta.csv)

**Comment by metachris** [comment]
Thanks, super helpful! Just yesterday evening we've backfilled all previous days with inclusion status, and discarded transactions that were included more then 12 seconds before receiving! I just checked a few transactions from your CSV @0xJchen and couldn't find them anymore.
