### ISSUE TITLE
No Fiber Comparison in latest release

### ISSUE THREAD

**Issue by dean-valentine** [flashbots/mempool-dumpster#34]
Doesn't include fiber anymore in the results: https://mempool-dumpster.flashbots.net/ethereum/mainnet/2024-02/2024-02-18_summary.txt

**Comment by metachris** [comment]
Thanks for the report!

Fiber stopped sending transactions and needed a restart. It's back in now: https://mempool-dumpster.flashbots.net/ethereum/mainnet/2024-02/2024-02-19_summary.txt
