### ISSUE TITLE
Store raw transactions in parquet instead of .csv.zip

### ISSUE THREAD

**Issue by dvush** [flashbots/mempool-dumpster#5]
# Intro

Compressed parquet file has advantages over zipped csv file.

1. Its a bit more space efficient
2. It allows efficient querying over compressed files

For example, lets say we want to query tx from some timestamp range:

With csv we need to either:
* store zipped file but decompress all files that might contain your tx. one decompression of the typical day file is around ~10 seconds
* store raw csv files and use 3x more disc space

With compressed parquet its better in space than zip and we get faster queries than raw csv:
* we get faster queries over time range (faster than reading raw csv, because unlike raw csv you can access concrete pages of the parquet that may contain your data)
* we store compressed file on disk and its compression is more efficient than zip of csv

## Exapmle

Files are written using polars-rs and schema is (note hash and raw_tx are stored as bytes and not hex strings)
```
Metadata for file: 2023-09-05_transactions.csv.zstd.parquet

version: 2
num of rows: 1191953
created by: Arrow2 - Native Rust implementation of Arrow
metadata:
  ARROW:schema: //////0AAAAEAAAA8v///xQAAAAEAAEAAAAKAAsACAAKAAQA+P///wwAAAAIAAgAAAAEAAMAAACEAAAARAAAAAQAAADs////LAAAACAAAAAYAAAAARMAABAAEgAEABAAEQAIAAAADAAAAAAA/P///wQABAAGAAAAcmF3X3R4AADs////LAAAACAAAAAYAAAAARMAABAAEgAEABAAEQAIAAAADAAAAAAA/P///wQABAAEAAAAaGFzaAAAAADs////NAAAACAAAAAYAAAAAQIAABAAEgAEABAAEQAIAAAADAAAAAAA9v///0AAAAAAAAYACAAEAAwAAAB0aW1lc3RhbXBfbXMA
message root {
  OPTIONAL INT64 timestamp_ms (INTEGER(64,false));
  OPTIONAL BYTE_ARRAY hash;
  OPTIONAL BYTE_ARRAY raw_tx;
}
```

```
# currently used files
2.5G 2023-09-05_transactions.csv 
824M 2023-09-05_transactions.csv.zip

# parquets with different compression types, first one is uncompressed
1.2G 2023-09-05_transactions.csv.parquet
661M 2023-09-05_transactions.csv.zstd.parquet
696M 2023-09-05_transactions.csv.brotli.parquet
705M 2023-09-05_transactions.csv.gzip.parquet
767M 2023-09-05_transactions.csv.lz4raw.parquet
771M 2023-09-05_transactions.csv.snappy.parquet
```

Compression and write time:
```
Finished writing file: "./data/2023-09-05_transactions.csv.parquet", size: 1249549959, time: 1.335191337s
Finished writing file: "./data/2023-09-05_transactions.csv.snappy.parquet", size: 771127935, time: 2.082866659s
Finished writing file: "./data/2023-09-05_transactions.csv.gzip.parquet", size: 704524483, time: 40.695586045s
Finished writing file: "./data/2023-09-05_transactions.csv.brotli.parquet", size: 696242555, time: 7.958041082s
Finished writing file: "./data/2023-09-05_transactions.csv.zstd.parquet", size: 660789742, time: 4.950803066s
Finished writing file: "./data/2023-09-05_transactions.csv.lz4raw.parquet", size: 766614700, time: 2.241794077s
```

Here we see that the most efficient and decently fast format is zstd but all compressions are pretty good.

Speed of querying can be tested with duckdb
```sql
-- run from cli (duckdb)
-- almost instant
select hash from '2023-09-05_transactions.csv.zstd.parquet' where timestamp_ms > 1693873717486 and timestamp_ms < 1693873754302;
-- also fast for some reason
select * from '2023-09-05_transactions.csv.zstd.parquet' where hash = from_hex('9bcc26a4c92e16128cda53c70e61c8393d2e02a3560573fe3f42165e42d61a91') limit 1;
```

### Note

For some reason querying for concrete tx hash is also fast over this file (produces by polars-rs)
```
select * from '2023-09-05_transactions.csv.zstd.parquet' where hash = from_hex('9bcc26a4c92e16128cda53c70e61c8393d2e02a3560573fe3f42165e42d61a91') limit 1;
```

but when I query metadata parquet file provided by the mempool dumpster its very slow, even though the file is 7 times smaller.
```
select * from '2023-09-05.parquet' where hash = '0x9bcc26a4c92e16128cda53c70e61c8393d2e02a3560573fe3f42165e42d61a91' limit 1;
```

**Comment by metachris** [comment]
interesting! i've not worked with parquet before and basically just followed some example code and let it be. for reference:

- data stucture: https://github.com/flashbots/mempool-dumpster/blob/main/common/types.go#L10
- parquet writing: https://github.com/flashbots/mempool-dumpster/blob/main/cmd/merge/transactions.go#L77-L99
- parquet library: https://github.com/xitongsys/parquet-go

happy to hear about optimizations! it's v easy to recreate, just use a file with raw transactions (i.e. a daily archive) and run `go run cmd/merge/* t <filename>` and it will spit out the parquet in `out/metadata.parquet`

we could certainly store the daily archive in parquet, along with all the extracted metadata 🤔

**Comment by metachris** [comment]
implemented, thanks @dvush 👍
